import pandas as pd
from sklearn.ensemble import RandomForestRegressor
import joblib

def train_model():
    # Load the data generated by data_gen.py
    df = pd.read_csv('sales_data.csv')
    
    # FIX: Convert 'date' column to actual datetime objects
    df['date'] = pd.to_datetime(df['date'])
    
    # Feature Engineering: Extract numbers the model can understand
    df['day_of_year'] = df['date'].dt.dayofyear
    df['day_of_week'] = df['date'].dt.dayofweek
    
    X = df[['day_of_year', 'day_of_week']]
    y = df['sales']
    
    # Initialize and train the model
    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X, y)
    
    # Save the trained model to a file
    joblib.dump(model, 'demand_model.pkl')
    print("✅ Model trained and saved as 'demand_model.pkl'!")

if __name__ == "__main__":
    train_model()